-- ============================================================
-- WEINKELLER DATENBANK SETUP
-- Diesen Code im Supabase SQL Editor ausfuehren
-- Dashboard > SQL Editor > New Query > Code einfuegen > Run
-- ============================================================

-- 1. WEINE TABELLE
create table if not exists wines (
  id           bigint generated by default as identity primary key,
  name         text not null,
  colour       text not null default 'red',
  year         integer,
  winery       text,
  country      text,
  region       text,
  grape        text,
  amount       integer not null default 1,
  best_between text,
  occasion     text not null default 'green',
  rationale    text,
  market_price numeric(10,2),
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

-- 2. EINKAUFSLISTE TABELLE
create table if not exists shopping_list (
  id         bigint generated by default as identity primary key,
  name       text not null,
  bought     boolean not null default false,
  notes      text,
  created_at timestamptz default now()
);

-- 3. ROW LEVEL SECURITY (RLS) AKTIVIEREN
alter table wines enable row level security;
alter table shopping_list enable row level security;

-- 4. POLICIES: Zugriff mit dem anon key erlauben
create policy "Allow all for anon" on wines
  for all using (true) with check (true);

create policy "Allow all for anon" on shopping_list
  for all using (true) with check (true);

-- ============================================================
-- FERTIG! Deine Datenbank ist bereit.
-- ============================================================
